remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ttrpg Sett
description: Development Diaries for building a mythic xenofiction ttrpg. 
show_downloads: false